# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 03:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wishlist', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=100)),
                ('date_added', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
