# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_date_hired'),
        ('wishlist', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wished_by',
            field=models.ManyToManyField(blank=True, to='login.User'),
        ),
    ]
